<a href="https://colab.research.google.com/github/manishkolla/Data-Structures/blob/main/Test_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Q-1

In [ ]:
def word_frequency(str):
  '''
  taking a sentence as input from the user and splitting it and appending them to list and then looping though the list to get the count
  or frequency of each word in that list and appendind all the data into a dictionary
  '''
  words=str.split()
  words_list=list(set(words))
  count=[]
  for i in range(len(words_list)):
    count.append(words.count(words_list[i]))
    words_dict=dict(zip(words_list,count))
  print (words_dict)
sentence=input('Enter stentence to count words frequency: ')
word_frequency(sentence)

Enter stentence to count words frequency: hi hi hi one two two ...
{'hi': 3, 'one': 1, '...': 1, 'two': 2}


###Q2

In [ ]:
import numpy as np
class Matrix_add_multiple():
#Taking the number of columns and rows as input from the user and looping through the numbers and taking array numbers as input and appending
#them to a list of lists and converting into a numpy array and doing the same technique twice to take 2 arrays and add and mutiply them
#checking the sizes of array, whether or not they satisfy thr condition for matrix addition and multiplication
  ele_list=[[],[],[]]
  columns= int(input("How many columns: "))
  rows=int(input("How many rows: "))
  for x in range(rows):
    for y in range(columns):
      ele=int(input("Enter a value: "))
      ele_list[x].append(ele)
  array_one=np.array(ele_list)
  print()
  print("Second Array")
  print()
  ele_list_2=[[],[],[]]
  columns_2= int(input("How many columns: "))
  rows_2=int(input("How many rows: "))
  for i in range(rows_2):
    for j in range(columns_2):
      ele_2=int(input("Enter a value: "))
      ele_list_2[i].append(ele_2)
  array_two=np.array(ele_list_2)

  print("The first array is \n", array_one)
  print("The second array is \n", array_two)
  print()
  if columns!=columns_2 and rows!=rows_2:
    print("Matrix addition is not possible")
  else:
    print("The sum of both the arrays is \n", array_one+array_two)
  print()
  if columns!=rows_2:
    print("Multiplication is not possible")
  else:
    print("The product of both the arrays is \n", array_one*array_two)
      

How many columns: 3
How many rows: 3
Enter a value: 1
Enter a value: 2
Enter a value: 3
Enter a value: 4
Enter a value: 5
Enter a value: 6
Enter a value: 7
Enter a value: 8
Enter a value: 9

Second Array

How many columns: 3
How many rows: 3
Enter a value: 0
Enter a value: 1
Enter a value: 0
Enter a value: 0
Enter a value: 2
Enter a value: 0
Enter a value: 0
Enter a value: 3
Enter a value: 0
The first array is 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The second array is 
 [[0 1 0]
 [0 2 0]
 [0 3 0]]

The sum of both the arrays is 
 [[ 1  3  3]
 [ 4  7  6]
 [ 7 11  9]]

The product of both the arrays is 
 [[ 0  2  0]
 [ 0 10  0]
 [ 0 24  0]]


###Q-3

In [ ]:
'''
The fastest algorithm is address this question is
(1)find sum of all numbers from 1 to (N-1) using formula, integerSum= [N*(N-1)]/2;                   Time complexity=O(log(n))
(2)calculate sum of all elements in Arry A[1...N] using a Loop or sum function ;                      Time complexity=O(log(n))
(3)Find the difference diff = (arraySum - integerSum), which is the integer in A that is repeated;   Time complexity=O(N)
(4)Print (diff) 

Time complexity = O(N)
'''


###Q-4

In [ ]:
'''
nested looping through the list of lists and adding the numbers to a variable and printing it at the end
'''
list_of_lists = [[1, 2, 3], [4, 5], [6], [7, 8, 9, 10]]
total = 0
for x in list_of_lists:
  for y in x:    
    total+=y  
print(total)   

55


###Q-5

In [ ]:
def powerSet(string, index, current):
    if index == len(string):
      print(current)
      return
    powerSet(string, index + 1, current + string[index])
    powerSet(string, index + 1, current)

elements= input("Enter a word or set of elements to find its powerset: ")
powerSet(elements, 0, "")

Enter a word or set of elements to find its powerset: abc
abc
ab
ac
a
bc
b
c



##Q-6


In [ ]:
'''
Algorithm:

Input : N (no. of disks)
Output: Moving N disks from a to c

TowerOfHonoi(N, a, b, c):
  if N = 1: 
    Move only disk from a to c         
  Otherwise
    Move N-1 disks from a to b using c as temporary storage i.e, TowerOfHonoi(N-1, a, c, b)
    Move Nth disk from a to c
    Move N-1 disks from b to c using a as temporary storage t.e, TowerOfHonoi(N-1, b, a, c)

Pseudo code:

Function TowerOfHonoi(N, a, b, c):         
  if N == 1:
    move disk from a to c
  ELSE:
    TowerOfHonoi(N - 1, a, c, b)
    move Nth disk from a to c            
    TowerOfHonoi(N - 1, b, a, c)

'''

###Q-7

In [ ]:
def reverse_string(string):
  '''
  Taking a string from the user and then using recursion and looping the string from back
  '''
  if string!="":
    reverse_string(string[1:])
    print(string[0],end="")

sentence= input("Enter a sentence to reverse: ")
reverse_string(sentence)

Enter a sentence to reverse: pots&pans
snap&stop

##Q-8

In [ ]:
'''
Part 1

The bottles are labelled from 1 to n.
Let there be n cups. Label the cups from 1 to n.
Pour the wine from bottle n to the cup . 
i.e Bottle 1 is poured in cup 1, Bottle 2 is poured in cup 2....... , Bottle n is poured in cup n.
Map the taste testers to the respective cups.
i.e Tester 1 tastes in cup 1, Tester 2 tastes in cup 2..............., Tester n tastes in cup n
In one month one of the testers will be dead. 
Except that corresponding bottle to the tester, the rest are not poisioned

Part 2
The bottles are labelled from 1 to n in binary. Example is shown below:      
Bottle 1	0000
Bottle 2	0001
Bottle 3	0010
Bottle 4	0011
Bottle 5	0100
Bottle 6	0101
Bottle 7	0110
Bottle 8	0111
Bottle 9	1000
Bottle 10	1001
Let there be log2n cups. Label the cups from 1 to log2n.
Pour a drop of the wine from all the bottles whose kth bit in the code is 1 to the cup n. 
From each bottle whose first bit is 1, a drop  is poured to cup 1.
From each bottle whose second bit is 1, a drop  is poured to cup 2.
From each bottle whose third bit is 1, a drop  is poured to cup 3.
From each bottle whose log2kth bit is 1, a drop  is poured to cup log2k.

Map the taste testers to the respective cups.
i.e Tester 1 tastes in cup 1, Tester 2 tastes in cup 2, tester 3 tastes in cup 3........
In one month some  of the testers will be dead. 
The wine that was present in the cups of all the dead testers is the poisoned wine.
'''

###Q-9

In [ ]:
'''
Let us consider an array A of n elements. We declare two variables max and min representing maximum and minimum elements. We have 2 cases.
If n is odd, then we initialise min and max elements as A[0], else we initialise max and min as the maximum and minimum of A[0] and A[1] respectively.
Starting with the next index in each case, we iterate through the arrays with increments of two. We basically check in pairs. If A[i] is greater than A[i+1], then A[i] is a candidate for maximum and A[i+1] is a candidate for minimum. Hence we check for these respectively. This takes 3 comparisons whatever be the case. 
Similar is the case when A[i] is less than A[i+1], here A[i] is a candidate for minimum and A[i+1] is a candidate for maximum.
As each step takes 3 comparisons and we iterate through the array in increments of 2, the total number of comparisons is less than 3*(n/2).

Infact, the exact number of comparisons are as follows:
If n is odd: 3*(n-1)/2

If n is even: (3n/2) -2
'''

##Q-10

In [15]:
print("    /-/ `\     ")
print(">\   |@@    |-__ ")
print("\ _/      |        `\ ")
print(" ___/_/         | h   ")
print("       |        \   | h  ")
print("       | |___\  |     ")
print("       ||        ||    ")

    /-/ `\     
>\   |@@    |-__ 
\ _/      |        `\ 
 ___/_/         | h   
       |        \   | h  
       | |___\  |     
       ||        ||    
